version: '2'
services:
  dns:
    image: lancachenet/lancache-dns:latest
    env_file: .env
    networks:
      dns-server_steam-cache:
    ports:
      - "192.168.68.11:53:53/tcp"
      - "192.168.68.11:53:53/udp"
    restart: always
## HTTPS requests are now handled in monolithic directly
## you could choose to return to sniproxy if desired
#
#  sniproxy:
#    image: lancachenet/sniproxy:latest
#    env_file: .env
#    restart: *restart-policy
#    ports:
#      - 443:443/tcp

  monolithic:
    image: lancachenet/monolithic:latest
    env_file: .env
    ports:
#      - 192.168.68.11:80:80/tcp
      - 443:443/tcp
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:/data/logs
    restart: always
networks:
  dns-server_steam-cache:
    external: true
